# Generated by Django 2.0.2 on 2018-05-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180530_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='c_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='bannerinfo',
            old_name='c_time',
            new_name='createtime',
        ),
    ]
